#include "RenderSystem.h"

#define BEGIN_VERTEX_DECLARATION(Type) \
	LPDIRECT3DVERTEXDECLARATION9 Type::declaration = 0; \
struct VertexDeclaration_##Type { \
	VertexDeclaration_##Type() { \
	static D3DVERTEXELEMENT9 elements[] = {

#define END_VERTEX_DECLARATION(Type) \
	, D3DDECL_END() \
	}; \
	RenderSystem::RegisterVertexDeclaration(Type::declaration, elements); \
	} \
} vertexDeclaration_##Type;

BEGIN_VERTEX_DECLARATION(VertexXYZNDT1)
{ 0, 0,  D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 }, 
{ 0, 12, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL, 0 },
{ 0, 24, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0 },
{ 0, 28, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT,      D3DDECLUSAGE_TEXCOORD, 0 }
END_VERTEX_DECLARATION(VertexXYZNDT1)

BEGIN_VERTEX_DECLARATION(VertexXYZWDT1)
{ 0, 0,  D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITIONT, 0 },
{ 0, 16, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR, 0 },
{ 0, 20, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT,      D3DDECLUSAGE_TEXCOORD, 0 }
END_VERTEX_DECLARATION(VertexXYZWDT1)
